name: Package Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests
        run: |
          uv run --all-extras pytest

      - name: Check
        run: |
          uv run --all-extras ruff check countrycode tests
          uv run --all-extras ruff format countrycode
          uv run --all-extras ruff format tests

