name: CI Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    strategy:
      fail-fast: true
      matrix:
        python:
          - "3.9"
          - "3.11"
          - "3.12"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python v${{ matrix.python}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests
        run: |
          uv run pytest --all-extras
